//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automatrix.Menu.Service.Test.USWarrantyForm {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", ConfigurationName="USWarrantyForm.UswcWebServiceSoap")]
    public interface UswcWebServiceSoap {
        
        // CODEGEN: Generating message contract since message GetDealerCodeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/GetDealerCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyForm.GetDealerCodeResponse GetDealerCode(Automatrix.Menu.Service.Test.USWarrantyForm.GetDealerCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/GetDealerCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetDealerCodeResponse> GetDealerCodeAsync(Automatrix.Menu.Service.Test.USWarrantyForm.GetDealerCodeRequest request);
        
        // CODEGEN: Generating message contract since message UpdateDealerCodeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/UpdateDealerCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyForm.UpdateDealerCodeResponse UpdateDealerCode(Automatrix.Menu.Service.Test.USWarrantyForm.UpdateDealerCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/UpdateDealerCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.UpdateDealerCodeResponse> UpdateDealerCodeAsync(Automatrix.Menu.Service.Test.USWarrantyForm.UpdateDealerCodeRequest request);
        
        // CODEGEN: Generating message contract since message GetPolicyNumRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/GetPolicyNum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyForm.GetPolicyNumResponse GetPolicyNum(Automatrix.Menu.Service.Test.USWarrantyForm.GetPolicyNumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/GetPolicyNum", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetPolicyNumResponse> GetPolicyNumAsync(Automatrix.Menu.Service.Test.USWarrantyForm.GetPolicyNumRequest request);
        
        // CODEGEN: Generating message contract since message GetVinInfoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/GetVinInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyForm.GetVinInfoResponse GetVinInfo(Automatrix.Menu.Service.Test.USWarrantyForm.GetVinInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/GetVinInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetVinInfoResponse> GetVinInfoAsync(Automatrix.Menu.Service.Test.USWarrantyForm.GetVinInfoRequest request);
        
        // CODEGEN: Generating message contract since message SubmitPolicyRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/SubmitPolicy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyResponse SubmitPolicy(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/SubmitPolicy", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyResponse> SubmitPolicyAsync(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyRequest request);
        
        // CODEGEN: Generating message contract since message SubmitProductsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/SubmitProducts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyForm.SubmitProductsResponse SubmitProducts(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/SubmitProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitProductsResponse> SubmitProductsAsync(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitProductsRequest request);
        
        // CODEGEN: Generating message contract since message VoidProductsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/VoidProducts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyForm.VoidProductsResponse VoidProducts(Automatrix.Menu.Service.Test.USWarrantyForm.VoidProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/VoidProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.VoidProductsResponse> VoidProductsAsync(Automatrix.Menu.Service.Test.USWarrantyForm.VoidProductsRequest request);
        
        // CODEGEN: Generating message contract since message SubmitPolicyCancelRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/SubmitPolicyCancel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyCancelResponse SubmitPolicyCancel(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyCancelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/SubmitPolicyCancel", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyCancelResponse> SubmitPolicyCancelAsync(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyCancelRequest request);
        
        // CODEGEN: Generating message contract since message ValidatePolicyCancelRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/ValidatePolicyCancel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyForm.ValidatePolicyCancelResponse ValidatePolicyCancel(Automatrix.Menu.Service.Test.USWarrantyForm.ValidatePolicyCancelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/ValidatePolicyCancel", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.ValidatePolicyCancelResponse> ValidatePolicyCancelAsync(Automatrix.Menu.Service.Test.USWarrantyForm.ValidatePolicyCancelRequest request);
        
        // CODEGEN: Generating message contract since message GetGapNumRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/GetGapNum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumResponse GetGapNum(Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/GetGapNum", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumResponse> GetGapNumAsync(Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumRequest request);
        
        // CODEGEN: Generating message contract since message GetGapNumWithPrefixRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/GetGapNumWithPrefix", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumWithPrefixResponse GetGapNumWithPrefix(Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumWithPrefixRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/GetGapNumWithPrefix", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumWithPrefixResponse> GetGapNumWithPrefixAsync(Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumWithPrefixRequest request);
        
        // CODEGEN: Generating message contract since message SubmitGapAddendumRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/SubmitGapAddendum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapAddendumResponse SubmitGapAddendum(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapAddendumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/SubmitGapAddendum", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapAddendumResponse> SubmitGapAddendumAsync(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapAddendumRequest request);
        
        // CODEGEN: Generating message contract since message SubmitGapCancelRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/SubmitGapCancel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapCancelResponse SubmitGapCancel(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapCancelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/SubmitGapCancel", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapCancelResponse> SubmitGapCancelAsync(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapCancelRequest request);
        
        // CODEGEN: Generating message contract since message ValidateGapCancelRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/ValidateGapCancel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyForm.ValidateGapCancelResponse ValidateGapCancel(Automatrix.Menu.Service.Test.USWarrantyForm.ValidateGapCancelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServicePolicies/ValidateGapCancel", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.ValidateGapCancelResponse> ValidateGapCancelAsync(Automatrix.Menu.Service.Test.USWarrantyForm.ValidateGapCancelRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
    public partial class AuthenticationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDealerCode", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class GetDealerCodeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
        public Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string DealerName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=1)]
        public string DealerAddr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=2)]
        public string DealerCity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=3)]
        public string DealerState;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=4)]
        public string DealerZip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=5)]
        public string DealerPhone;
        
        public GetDealerCodeRequest() {
        }
        
        public GetDealerCodeRequest(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerName, string DealerAddr, string DealerCity, string DealerState, string DealerZip, string DealerPhone) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.DealerName = DealerName;
            this.DealerAddr = DealerAddr;
            this.DealerCity = DealerCity;
            this.DealerState = DealerState;
            this.DealerZip = DealerZip;
            this.DealerPhone = DealerPhone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDealerCodeResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class GetDealerCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string GetDealerCodeResult;
        
        public GetDealerCodeResponse() {
        }
        
        public GetDealerCodeResponse(string GetDealerCodeResult) {
            this.GetDealerCodeResult = GetDealerCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDealerCode", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class UpdateDealerCodeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
        public Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=1)]
        public string DealerName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=2)]
        public string DealerAddr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=3)]
        public string DealerCity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=4)]
        public string DealerState;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=5)]
        public string DealerZip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=6)]
        public string DealerPhone;
        
        public UpdateDealerCodeRequest() {
        }
        
        public UpdateDealerCodeRequest(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string DealerName, string DealerAddr, string DealerCity, string DealerState, string DealerZip, string DealerPhone) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.DealerCode = DealerCode;
            this.DealerName = DealerName;
            this.DealerAddr = DealerAddr;
            this.DealerCity = DealerCity;
            this.DealerState = DealerState;
            this.DealerZip = DealerZip;
            this.DealerPhone = DealerPhone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDealerCodeResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class UpdateDealerCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string UpdateDealerCodeResult;
        
        public UpdateDealerCodeResponse() {
        }
        
        public UpdateDealerCodeResponse(string UpdateDealerCodeResult) {
            this.UpdateDealerCodeResult = UpdateDealerCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPolicyNum", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class GetPolicyNumRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
        public Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=1)]
        public string DealerCode;
        
        public GetPolicyNumRequest() {
        }
        
        public GetPolicyNumRequest(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Company = Company;
            this.DealerCode = DealerCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPolicyNumResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class GetPolicyNumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string GetPolicyNumResult;
        
        public GetPolicyNumResponse() {
        }
        
        public GetPolicyNumResponse(string GetPolicyNumResult) {
            this.GetPolicyNumResult = GetPolicyNumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVinInfo", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class GetVinInfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
        public Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string Vin;
        
        public GetVinInfoRequest() {
        }
        
        public GetVinInfoRequest(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string Vin) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Vin = Vin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVinInfoResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class GetVinInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string GetVinInfoResult;
        
        public GetVinInfoResponse() {
        }
        
        public GetVinInfoResponse(string GetVinInfoResult) {
            this.GetVinInfoResult = GetVinInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitPolicy", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class SubmitPolicyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
        public Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=1)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=2)]
        public string WarrantyNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=3)]
        public string FirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=4)]
        public string LastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=5)]
        public string Address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=6)]
        public string City;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=7)]
        public string State;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=8)]
        public string Zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=9)]
        public string Phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=10)]
        public string EmailAddr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=11)]
        public string RetailAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=12)]
        public string Vin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=13)]
        public string TermMonths;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=14)]
        public string TermMiles;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=15)]
        public string Deductible;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=16)]
        public string EffMiles;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=17)]
        public string EffDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=18)]
        public string Plan;
        
        public SubmitPolicyRequest() {
        }
        
        public SubmitPolicyRequest(
                    Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, 
                    string Company, 
                    string DealerCode, 
                    string WarrantyNum, 
                    string FirstName, 
                    string LastName, 
                    string Address, 
                    string City, 
                    string State, 
                    string Zip, 
                    string Phone, 
                    string EmailAddr, 
                    string RetailAmount, 
                    string Vin, 
                    string TermMonths, 
                    string TermMiles, 
                    string Deductible, 
                    string EffMiles, 
                    string EffDate, 
                    string Plan) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Company = Company;
            this.DealerCode = DealerCode;
            this.WarrantyNum = WarrantyNum;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Address = Address;
            this.City = City;
            this.State = State;
            this.Zip = Zip;
            this.Phone = Phone;
            this.EmailAddr = EmailAddr;
            this.RetailAmount = RetailAmount;
            this.Vin = Vin;
            this.TermMonths = TermMonths;
            this.TermMiles = TermMiles;
            this.Deductible = Deductible;
            this.EffMiles = EffMiles;
            this.EffDate = EffDate;
            this.Plan = Plan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitPolicyResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class SubmitPolicyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string SubmitPolicyResult;
        
        public SubmitPolicyResponse() {
        }
        
        public SubmitPolicyResponse(string SubmitPolicyResult) {
            this.SubmitPolicyResult = SubmitPolicyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitProducts", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class SubmitProductsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
        public Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public System.Xml.XmlNode xmlDoc;
        
        public SubmitProductsRequest() {
        }
        
        public SubmitProductsRequest(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, System.Xml.XmlNode xmlDoc) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitProductsResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class SubmitProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string SubmitProductsResult;
        
        public SubmitProductsResponse() {
        }
        
        public SubmitProductsResponse(string SubmitProductsResult) {
            this.SubmitProductsResult = SubmitProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VoidProducts", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class VoidProductsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
        public Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public System.Xml.XmlNode xmlDoc;
        
        public VoidProductsRequest() {
        }
        
        public VoidProductsRequest(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, System.Xml.XmlNode xmlDoc) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VoidProductsResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class VoidProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string VoidProductsResult;
        
        public VoidProductsResponse() {
        }
        
        public VoidProductsResponse(string VoidProductsResult) {
            this.VoidProductsResult = VoidProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitPolicyCancel", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class SubmitPolicyCancelRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
        public Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=1)]
        public string WarrantyNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=2)]
        public System.DateTime CancelDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=3)]
        public string CancelMiles;
        
        public SubmitPolicyCancelRequest() {
        }
        
        public SubmitPolicyCancelRequest(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string Company, string WarrantyNum, System.DateTime CancelDate, string CancelMiles) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Company = Company;
            this.WarrantyNum = WarrantyNum;
            this.CancelDate = CancelDate;
            this.CancelMiles = CancelMiles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitPolicyCancelResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class SubmitPolicyCancelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string SubmitPolicyCancelResult;
        
        public SubmitPolicyCancelResponse() {
        }
        
        public SubmitPolicyCancelResponse(string SubmitPolicyCancelResult) {
            this.SubmitPolicyCancelResult = SubmitPolicyCancelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidatePolicyCancel", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class ValidatePolicyCancelRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
        public Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=1)]
        public string WarrantyNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=2)]
        public System.DateTime CancelDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=3)]
        public string CancelMiles;
        
        public ValidatePolicyCancelRequest() {
        }
        
        public ValidatePolicyCancelRequest(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string Company, string WarrantyNum, System.DateTime CancelDate, string CancelMiles) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Company = Company;
            this.WarrantyNum = WarrantyNum;
            this.CancelDate = CancelDate;
            this.CancelMiles = CancelMiles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidatePolicyCancelResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class ValidatePolicyCancelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string ValidatePolicyCancelResult;
        
        public ValidatePolicyCancelResponse() {
        }
        
        public ValidatePolicyCancelResponse(string ValidatePolicyCancelResult) {
            this.ValidatePolicyCancelResult = ValidatePolicyCancelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGapNum", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class GetGapNumRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
        public Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string DealerCode;
        
        public GetGapNumRequest() {
        }
        
        public GetGapNumRequest(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.DealerCode = DealerCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGapNumResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class GetGapNumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string GetGapNumResult;
        
        public GetGapNumResponse() {
        }
        
        public GetGapNumResponse(string GetGapNumResult) {
            this.GetGapNumResult = GetGapNumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGapNumWithPrefix", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class GetGapNumWithPrefixRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
        public Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=1)]
        public string Prefix;
        
        public GetGapNumWithPrefixRequest() {
        }
        
        public GetGapNumWithPrefixRequest(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string Prefix) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.DealerCode = DealerCode;
            this.Prefix = Prefix;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGapNumWithPrefixResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class GetGapNumWithPrefixResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string GetGapNumWithPrefixResult;
        
        public GetGapNumWithPrefixResponse() {
        }
        
        public GetGapNumWithPrefixResponse(string GetGapNumWithPrefixResult) {
            this.GetGapNumWithPrefixResult = GetGapNumWithPrefixResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitGapAddendum", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class SubmitGapAddendumRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
        public Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=1)]
        public string GapNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=2)]
        public string FirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=3)]
        public string LastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=4)]
        public string Address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=5)]
        public string Zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=6)]
        public string Phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=7)]
        public string EmailAddr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=8)]
        public string RetailAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=9)]
        public string Vin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=10)]
        public string TermMonths;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=11)]
        public string EffDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=12)]
        public string FinancedAmount;
        
        public SubmitGapAddendumRequest() {
        }
        
        public SubmitGapAddendumRequest(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string GapNumber, string FirstName, string LastName, string Address, string Zip, string Phone, string EmailAddr, string RetailAmount, string Vin, string TermMonths, string EffDate, string FinancedAmount) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.DealerCode = DealerCode;
            this.GapNumber = GapNumber;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Address = Address;
            this.Zip = Zip;
            this.Phone = Phone;
            this.EmailAddr = EmailAddr;
            this.RetailAmount = RetailAmount;
            this.Vin = Vin;
            this.TermMonths = TermMonths;
            this.EffDate = EffDate;
            this.FinancedAmount = FinancedAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitGapAddendumResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class SubmitGapAddendumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string SubmitGapAddendumResult;
        
        public SubmitGapAddendumResponse() {
        }
        
        public SubmitGapAddendumResponse(string SubmitGapAddendumResult) {
            this.SubmitGapAddendumResult = SubmitGapAddendumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitGapCancel", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class SubmitGapCancelRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
        public Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=1)]
        public string GapNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=2)]
        public System.DateTime CancelDate;
        
        public SubmitGapCancelRequest() {
        }
        
        public SubmitGapCancelRequest(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string GapNumber, System.DateTime CancelDate) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.DealerCode = DealerCode;
            this.GapNumber = GapNumber;
            this.CancelDate = CancelDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitGapCancelResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class SubmitGapCancelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string SubmitGapCancelResult;
        
        public SubmitGapCancelResponse() {
        }
        
        public SubmitGapCancelResponse(string SubmitGapCancelResult) {
            this.SubmitGapCancelResult = SubmitGapCancelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateGapCancel", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class ValidateGapCancelRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies")]
        public Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=1)]
        public string GapNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=2)]
        public System.DateTime CancelDate;
        
        public ValidateGapCancelRequest() {
        }
        
        public ValidateGapCancelRequest(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string GapNumber, System.DateTime CancelDate) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.DealerCode = DealerCode;
            this.GapNumber = GapNumber;
            this.CancelDate = CancelDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateGapCancelResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServicePolicies", IsWrapped=true)]
    public partial class ValidateGapCancelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServicePolicies", Order=0)]
        public string ValidateGapCancelResult;
        
        public ValidateGapCancelResponse() {
        }
        
        public ValidateGapCancelResponse(string ValidateGapCancelResult) {
            this.ValidateGapCancelResult = ValidateGapCancelResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UswcWebServiceSoapChannel : Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UswcWebServiceSoapClient : System.ServiceModel.ClientBase<Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap>, Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap {
        
        public UswcWebServiceSoapClient() {
        }
        
        public UswcWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UswcWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UswcWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UswcWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyForm.GetDealerCodeResponse Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.GetDealerCode(Automatrix.Menu.Service.Test.USWarrantyForm.GetDealerCodeRequest request) {
            return base.Channel.GetDealerCode(request);
        }
        
        public string GetDealerCode(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerName, string DealerAddr, string DealerCity, string DealerState, string DealerZip, string DealerPhone) {
            Automatrix.Menu.Service.Test.USWarrantyForm.GetDealerCodeRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.GetDealerCodeRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.DealerName = DealerName;
            inValue.DealerAddr = DealerAddr;
            inValue.DealerCity = DealerCity;
            inValue.DealerState = DealerState;
            inValue.DealerZip = DealerZip;
            inValue.DealerPhone = DealerPhone;
            Automatrix.Menu.Service.Test.USWarrantyForm.GetDealerCodeResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).GetDealerCode(inValue);
            return retVal.GetDealerCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetDealerCodeResponse> Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.GetDealerCodeAsync(Automatrix.Menu.Service.Test.USWarrantyForm.GetDealerCodeRequest request) {
            return base.Channel.GetDealerCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetDealerCodeResponse> GetDealerCodeAsync(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerName, string DealerAddr, string DealerCity, string DealerState, string DealerZip, string DealerPhone) {
            Automatrix.Menu.Service.Test.USWarrantyForm.GetDealerCodeRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.GetDealerCodeRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.DealerName = DealerName;
            inValue.DealerAddr = DealerAddr;
            inValue.DealerCity = DealerCity;
            inValue.DealerState = DealerState;
            inValue.DealerZip = DealerZip;
            inValue.DealerPhone = DealerPhone;
            return ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).GetDealerCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyForm.UpdateDealerCodeResponse Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.UpdateDealerCode(Automatrix.Menu.Service.Test.USWarrantyForm.UpdateDealerCodeRequest request) {
            return base.Channel.UpdateDealerCode(request);
        }
        
        public string UpdateDealerCode(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string DealerName, string DealerAddr, string DealerCity, string DealerState, string DealerZip, string DealerPhone) {
            Automatrix.Menu.Service.Test.USWarrantyForm.UpdateDealerCodeRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.UpdateDealerCodeRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.DealerCode = DealerCode;
            inValue.DealerName = DealerName;
            inValue.DealerAddr = DealerAddr;
            inValue.DealerCity = DealerCity;
            inValue.DealerState = DealerState;
            inValue.DealerZip = DealerZip;
            inValue.DealerPhone = DealerPhone;
            Automatrix.Menu.Service.Test.USWarrantyForm.UpdateDealerCodeResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).UpdateDealerCode(inValue);
            return retVal.UpdateDealerCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.UpdateDealerCodeResponse> Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.UpdateDealerCodeAsync(Automatrix.Menu.Service.Test.USWarrantyForm.UpdateDealerCodeRequest request) {
            return base.Channel.UpdateDealerCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.UpdateDealerCodeResponse> UpdateDealerCodeAsync(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string DealerName, string DealerAddr, string DealerCity, string DealerState, string DealerZip, string DealerPhone) {
            Automatrix.Menu.Service.Test.USWarrantyForm.UpdateDealerCodeRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.UpdateDealerCodeRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.DealerCode = DealerCode;
            inValue.DealerName = DealerName;
            inValue.DealerAddr = DealerAddr;
            inValue.DealerCity = DealerCity;
            inValue.DealerState = DealerState;
            inValue.DealerZip = DealerZip;
            inValue.DealerPhone = DealerPhone;
            return ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).UpdateDealerCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyForm.GetPolicyNumResponse Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.GetPolicyNum(Automatrix.Menu.Service.Test.USWarrantyForm.GetPolicyNumRequest request) {
            return base.Channel.GetPolicyNum(request);
        }
        
        public string GetPolicyNum(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode) {
            Automatrix.Menu.Service.Test.USWarrantyForm.GetPolicyNumRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.GetPolicyNumRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            Automatrix.Menu.Service.Test.USWarrantyForm.GetPolicyNumResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).GetPolicyNum(inValue);
            return retVal.GetPolicyNumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetPolicyNumResponse> Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.GetPolicyNumAsync(Automatrix.Menu.Service.Test.USWarrantyForm.GetPolicyNumRequest request) {
            return base.Channel.GetPolicyNumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetPolicyNumResponse> GetPolicyNumAsync(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode) {
            Automatrix.Menu.Service.Test.USWarrantyForm.GetPolicyNumRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.GetPolicyNumRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            return ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).GetPolicyNumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyForm.GetVinInfoResponse Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.GetVinInfo(Automatrix.Menu.Service.Test.USWarrantyForm.GetVinInfoRequest request) {
            return base.Channel.GetVinInfo(request);
        }
        
        public string GetVinInfo(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string Vin) {
            Automatrix.Menu.Service.Test.USWarrantyForm.GetVinInfoRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.GetVinInfoRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Vin = Vin;
            Automatrix.Menu.Service.Test.USWarrantyForm.GetVinInfoResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).GetVinInfo(inValue);
            return retVal.GetVinInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetVinInfoResponse> Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.GetVinInfoAsync(Automatrix.Menu.Service.Test.USWarrantyForm.GetVinInfoRequest request) {
            return base.Channel.GetVinInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetVinInfoResponse> GetVinInfoAsync(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string Vin) {
            Automatrix.Menu.Service.Test.USWarrantyForm.GetVinInfoRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.GetVinInfoRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Vin = Vin;
            return ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).GetVinInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyResponse Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.SubmitPolicy(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyRequest request) {
            return base.Channel.SubmitPolicy(request);
        }
        
        public string SubmitPolicy(
                    Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, 
                    string Company, 
                    string DealerCode, 
                    string WarrantyNum, 
                    string FirstName, 
                    string LastName, 
                    string Address, 
                    string City, 
                    string State, 
                    string Zip, 
                    string Phone, 
                    string EmailAddr, 
                    string RetailAmount, 
                    string Vin, 
                    string TermMonths, 
                    string TermMiles, 
                    string Deductible, 
                    string EffMiles, 
                    string EffDate, 
                    string Plan) {
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.WarrantyNum = WarrantyNum;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.Address = Address;
            inValue.City = City;
            inValue.State = State;
            inValue.Zip = Zip;
            inValue.Phone = Phone;
            inValue.EmailAddr = EmailAddr;
            inValue.RetailAmount = RetailAmount;
            inValue.Vin = Vin;
            inValue.TermMonths = TermMonths;
            inValue.TermMiles = TermMiles;
            inValue.Deductible = Deductible;
            inValue.EffMiles = EffMiles;
            inValue.EffDate = EffDate;
            inValue.Plan = Plan;
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).SubmitPolicy(inValue);
            return retVal.SubmitPolicyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyResponse> Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.SubmitPolicyAsync(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyRequest request) {
            return base.Channel.SubmitPolicyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyResponse> SubmitPolicyAsync(
                    Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, 
                    string Company, 
                    string DealerCode, 
                    string WarrantyNum, 
                    string FirstName, 
                    string LastName, 
                    string Address, 
                    string City, 
                    string State, 
                    string Zip, 
                    string Phone, 
                    string EmailAddr, 
                    string RetailAmount, 
                    string Vin, 
                    string TermMonths, 
                    string TermMiles, 
                    string Deductible, 
                    string EffMiles, 
                    string EffDate, 
                    string Plan) {
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.WarrantyNum = WarrantyNum;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.Address = Address;
            inValue.City = City;
            inValue.State = State;
            inValue.Zip = Zip;
            inValue.Phone = Phone;
            inValue.EmailAddr = EmailAddr;
            inValue.RetailAmount = RetailAmount;
            inValue.Vin = Vin;
            inValue.TermMonths = TermMonths;
            inValue.TermMiles = TermMiles;
            inValue.Deductible = Deductible;
            inValue.EffMiles = EffMiles;
            inValue.EffDate = EffDate;
            inValue.Plan = Plan;
            return ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).SubmitPolicyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyForm.SubmitProductsResponse Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.SubmitProducts(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitProductsRequest request) {
            return base.Channel.SubmitProducts(request);
        }
        
        public string SubmitProducts(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, System.Xml.XmlNode xmlDoc) {
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitProductsRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.SubmitProductsRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.xmlDoc = xmlDoc;
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitProductsResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).SubmitProducts(inValue);
            return retVal.SubmitProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitProductsResponse> Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.SubmitProductsAsync(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitProductsRequest request) {
            return base.Channel.SubmitProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitProductsResponse> SubmitProductsAsync(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, System.Xml.XmlNode xmlDoc) {
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitProductsRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.SubmitProductsRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.xmlDoc = xmlDoc;
            return ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).SubmitProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyForm.VoidProductsResponse Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.VoidProducts(Automatrix.Menu.Service.Test.USWarrantyForm.VoidProductsRequest request) {
            return base.Channel.VoidProducts(request);
        }
        
        public string VoidProducts(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, System.Xml.XmlNode xmlDoc) {
            Automatrix.Menu.Service.Test.USWarrantyForm.VoidProductsRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.VoidProductsRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.xmlDoc = xmlDoc;
            Automatrix.Menu.Service.Test.USWarrantyForm.VoidProductsResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).VoidProducts(inValue);
            return retVal.VoidProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.VoidProductsResponse> Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.VoidProductsAsync(Automatrix.Menu.Service.Test.USWarrantyForm.VoidProductsRequest request) {
            return base.Channel.VoidProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.VoidProductsResponse> VoidProductsAsync(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, System.Xml.XmlNode xmlDoc) {
            Automatrix.Menu.Service.Test.USWarrantyForm.VoidProductsRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.VoidProductsRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.xmlDoc = xmlDoc;
            return ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).VoidProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyCancelResponse Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.SubmitPolicyCancel(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyCancelRequest request) {
            return base.Channel.SubmitPolicyCancel(request);
        }
        
        public string SubmitPolicyCancel(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string Company, string WarrantyNum, System.DateTime CancelDate, string CancelMiles) {
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyCancelRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyCancelRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.WarrantyNum = WarrantyNum;
            inValue.CancelDate = CancelDate;
            inValue.CancelMiles = CancelMiles;
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyCancelResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).SubmitPolicyCancel(inValue);
            return retVal.SubmitPolicyCancelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyCancelResponse> Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.SubmitPolicyCancelAsync(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyCancelRequest request) {
            return base.Channel.SubmitPolicyCancelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyCancelResponse> SubmitPolicyCancelAsync(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string Company, string WarrantyNum, System.DateTime CancelDate, string CancelMiles) {
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyCancelRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.SubmitPolicyCancelRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.WarrantyNum = WarrantyNum;
            inValue.CancelDate = CancelDate;
            inValue.CancelMiles = CancelMiles;
            return ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).SubmitPolicyCancelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyForm.ValidatePolicyCancelResponse Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.ValidatePolicyCancel(Automatrix.Menu.Service.Test.USWarrantyForm.ValidatePolicyCancelRequest request) {
            return base.Channel.ValidatePolicyCancel(request);
        }
        
        public string ValidatePolicyCancel(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string Company, string WarrantyNum, System.DateTime CancelDate, string CancelMiles) {
            Automatrix.Menu.Service.Test.USWarrantyForm.ValidatePolicyCancelRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.ValidatePolicyCancelRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.WarrantyNum = WarrantyNum;
            inValue.CancelDate = CancelDate;
            inValue.CancelMiles = CancelMiles;
            Automatrix.Menu.Service.Test.USWarrantyForm.ValidatePolicyCancelResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).ValidatePolicyCancel(inValue);
            return retVal.ValidatePolicyCancelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.ValidatePolicyCancelResponse> Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.ValidatePolicyCancelAsync(Automatrix.Menu.Service.Test.USWarrantyForm.ValidatePolicyCancelRequest request) {
            return base.Channel.ValidatePolicyCancelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.ValidatePolicyCancelResponse> ValidatePolicyCancelAsync(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string Company, string WarrantyNum, System.DateTime CancelDate, string CancelMiles) {
            Automatrix.Menu.Service.Test.USWarrantyForm.ValidatePolicyCancelRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.ValidatePolicyCancelRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.WarrantyNum = WarrantyNum;
            inValue.CancelDate = CancelDate;
            inValue.CancelMiles = CancelMiles;
            return ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).ValidatePolicyCancelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumResponse Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.GetGapNum(Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumRequest request) {
            return base.Channel.GetGapNum(request);
        }
        
        public string GetGapNum(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode) {
            Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.DealerCode = DealerCode;
            Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).GetGapNum(inValue);
            return retVal.GetGapNumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumResponse> Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.GetGapNumAsync(Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumRequest request) {
            return base.Channel.GetGapNumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumResponse> GetGapNumAsync(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode) {
            Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.DealerCode = DealerCode;
            return ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).GetGapNumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumWithPrefixResponse Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.GetGapNumWithPrefix(Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumWithPrefixRequest request) {
            return base.Channel.GetGapNumWithPrefix(request);
        }
        
        public string GetGapNumWithPrefix(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string Prefix) {
            Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumWithPrefixRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumWithPrefixRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.DealerCode = DealerCode;
            inValue.Prefix = Prefix;
            Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumWithPrefixResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).GetGapNumWithPrefix(inValue);
            return retVal.GetGapNumWithPrefixResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumWithPrefixResponse> Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.GetGapNumWithPrefixAsync(Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumWithPrefixRequest request) {
            return base.Channel.GetGapNumWithPrefixAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumWithPrefixResponse> GetGapNumWithPrefixAsync(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string Prefix) {
            Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumWithPrefixRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.GetGapNumWithPrefixRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.DealerCode = DealerCode;
            inValue.Prefix = Prefix;
            return ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).GetGapNumWithPrefixAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapAddendumResponse Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.SubmitGapAddendum(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapAddendumRequest request) {
            return base.Channel.SubmitGapAddendum(request);
        }
        
        public string SubmitGapAddendum(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string GapNumber, string FirstName, string LastName, string Address, string Zip, string Phone, string EmailAddr, string RetailAmount, string Vin, string TermMonths, string EffDate, string FinancedAmount) {
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapAddendumRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapAddendumRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.DealerCode = DealerCode;
            inValue.GapNumber = GapNumber;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.Address = Address;
            inValue.Zip = Zip;
            inValue.Phone = Phone;
            inValue.EmailAddr = EmailAddr;
            inValue.RetailAmount = RetailAmount;
            inValue.Vin = Vin;
            inValue.TermMonths = TermMonths;
            inValue.EffDate = EffDate;
            inValue.FinancedAmount = FinancedAmount;
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapAddendumResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).SubmitGapAddendum(inValue);
            return retVal.SubmitGapAddendumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapAddendumResponse> Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.SubmitGapAddendumAsync(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapAddendumRequest request) {
            return base.Channel.SubmitGapAddendumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapAddendumResponse> SubmitGapAddendumAsync(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string GapNumber, string FirstName, string LastName, string Address, string Zip, string Phone, string EmailAddr, string RetailAmount, string Vin, string TermMonths, string EffDate, string FinancedAmount) {
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapAddendumRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapAddendumRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.DealerCode = DealerCode;
            inValue.GapNumber = GapNumber;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.Address = Address;
            inValue.Zip = Zip;
            inValue.Phone = Phone;
            inValue.EmailAddr = EmailAddr;
            inValue.RetailAmount = RetailAmount;
            inValue.Vin = Vin;
            inValue.TermMonths = TermMonths;
            inValue.EffDate = EffDate;
            inValue.FinancedAmount = FinancedAmount;
            return ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).SubmitGapAddendumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapCancelResponse Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.SubmitGapCancel(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapCancelRequest request) {
            return base.Channel.SubmitGapCancel(request);
        }
        
        public string SubmitGapCancel(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string GapNumber, System.DateTime CancelDate) {
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapCancelRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapCancelRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.DealerCode = DealerCode;
            inValue.GapNumber = GapNumber;
            inValue.CancelDate = CancelDate;
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapCancelResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).SubmitGapCancel(inValue);
            return retVal.SubmitGapCancelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapCancelResponse> Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.SubmitGapCancelAsync(Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapCancelRequest request) {
            return base.Channel.SubmitGapCancelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapCancelResponse> SubmitGapCancelAsync(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string GapNumber, System.DateTime CancelDate) {
            Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapCancelRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.SubmitGapCancelRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.DealerCode = DealerCode;
            inValue.GapNumber = GapNumber;
            inValue.CancelDate = CancelDate;
            return ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).SubmitGapCancelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyForm.ValidateGapCancelResponse Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.ValidateGapCancel(Automatrix.Menu.Service.Test.USWarrantyForm.ValidateGapCancelRequest request) {
            return base.Channel.ValidateGapCancel(request);
        }
        
        public string ValidateGapCancel(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string GapNumber, System.DateTime CancelDate) {
            Automatrix.Menu.Service.Test.USWarrantyForm.ValidateGapCancelRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.ValidateGapCancelRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.DealerCode = DealerCode;
            inValue.GapNumber = GapNumber;
            inValue.CancelDate = CancelDate;
            Automatrix.Menu.Service.Test.USWarrantyForm.ValidateGapCancelResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).ValidateGapCancel(inValue);
            return retVal.ValidateGapCancelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.ValidateGapCancelResponse> Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap.ValidateGapCancelAsync(Automatrix.Menu.Service.Test.USWarrantyForm.ValidateGapCancelRequest request) {
            return base.Channel.ValidateGapCancelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyForm.ValidateGapCancelResponse> ValidateGapCancelAsync(Automatrix.Menu.Service.Test.USWarrantyForm.AuthenticationHeader AuthenticationHeader, string DealerCode, string GapNumber, System.DateTime CancelDate) {
            Automatrix.Menu.Service.Test.USWarrantyForm.ValidateGapCancelRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyForm.ValidateGapCancelRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.DealerCode = DealerCode;
            inValue.GapNumber = GapNumber;
            inValue.CancelDate = CancelDate;
            return ((Automatrix.Menu.Service.Test.USWarrantyForm.UswcWebServiceSoap)(this)).ValidateGapCancelAsync(inValue);
        }
    }
}
