//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automatrix.Menu.Service.Test.USWarrantyRates {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", ConfigurationName="USWarrantyRates.UswcWebServiceSoap")]
    public interface UswcWebServiceSoap {
        
        // CODEGEN: Generating message contract since message GetDentRatesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetDentRates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetDentRatesResponse GetDentRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetDentRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetDentRates", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetDentRatesResponse> GetDentRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetDentRatesRequest request);
        
        // CODEGEN: Generating message contract since message GetEwtRatesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetEwtRates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetEwtRatesResponse GetEwtRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetEwtRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetEwtRates", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetEwtRatesResponse> GetEwtRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetEwtRatesRequest request);
        
        // CODEGEN: Generating message contract since message GetKeyRatesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetKeyRates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetKeyRatesResponse GetKeyRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetKeyRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetKeyRates", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetKeyRatesResponse> GetKeyRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetKeyRatesRequest request);
        
        // CODEGEN: Generating message contract since message GetVscRatesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetVscRates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetVscRatesResponse GetVscRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetVscRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetVscRates", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetVscRatesResponse> GetVscRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetVscRatesRequest request);
        
        // CODEGEN: Generating message contract since message GetMaintRatesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetMaintRates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetMaintRatesResponse GetMaintRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetMaintRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetMaintRates", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetMaintRatesResponse> GetMaintRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetMaintRatesRequest request);
        
        // CODEGEN: Generating message contract since message GetRoadHazardRatesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetRoadHazardRates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetRoadHazardRatesResponse GetRoadHazardRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetRoadHazardRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetRoadHazardRates", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetRoadHazardRatesResponse> GetRoadHazardRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetRoadHazardRatesRequest request);
        
        // CODEGEN: Generating message contract since message GetGapRatesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetGapRates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetGapRatesResponse GetGapRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetGapRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetGapRates", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetGapRatesResponse> GetGapRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetGapRatesRequest request);
        
        // CODEGEN: Generating message contract since message GetEtchRatesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetEtchRates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetEtchRatesResponse GetEtchRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetEtchRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetEtchRates", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetEtchRatesResponse> GetEtchRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetEtchRatesRequest request);
        
        // CODEGEN: Generating message contract since message GetChemicalRatesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetChemicalRates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetChemicalRatesResponse GetChemicalRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetChemicalRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsWarranty.com/UswcWebServiceRates/GetChemicalRates", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetChemicalRatesResponse> GetChemicalRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetChemicalRatesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates")]
    public partial class AuthenticationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDentRates", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetDentRatesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates")]
        public Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=1)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=2)]
        public string Vin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=3)]
        public System.DateTime SaleDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=4)]
        public string Mileage;
        
        public GetDentRatesRequest() {
        }
        
        public GetDentRatesRequest(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Company = Company;
            this.DealerCode = DealerCode;
            this.Vin = Vin;
            this.SaleDate = SaleDate;
            this.Mileage = Mileage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDentRatesResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetDentRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string GetDentRatesResult;
        
        public GetDentRatesResponse() {
        }
        
        public GetDentRatesResponse(string GetDentRatesResult) {
            this.GetDentRatesResult = GetDentRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEwtRates", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetEwtRatesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates")]
        public Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=1)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=2)]
        public string Vin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=3)]
        public System.DateTime SaleDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=4)]
        public string Mileage;
        
        public GetEwtRatesRequest() {
        }
        
        public GetEwtRatesRequest(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Company = Company;
            this.DealerCode = DealerCode;
            this.Vin = Vin;
            this.SaleDate = SaleDate;
            this.Mileage = Mileage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEwtRatesResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetEwtRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string GetEwtRatesResult;
        
        public GetEwtRatesResponse() {
        }
        
        public GetEwtRatesResponse(string GetEwtRatesResult) {
            this.GetEwtRatesResult = GetEwtRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKeyRates", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetKeyRatesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates")]
        public Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=1)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=2)]
        public string Vin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=3)]
        public System.DateTime SaleDate;
        
        public GetKeyRatesRequest() {
        }
        
        public GetKeyRatesRequest(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Company = Company;
            this.DealerCode = DealerCode;
            this.Vin = Vin;
            this.SaleDate = SaleDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKeyRatesResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetKeyRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string GetKeyRatesResult;
        
        public GetKeyRatesResponse() {
        }
        
        public GetKeyRatesResponse(string GetKeyRatesResult) {
            this.GetKeyRatesResult = GetKeyRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVscRates", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetVscRatesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates")]
        public Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=1)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=2)]
        public string Vin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=3)]
        public System.DateTime SaleDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=4)]
        public string Mileage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=5)]
        public string NewUsed;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=6)]
        public System.DateTime InSrvDate;
        
        public GetVscRatesRequest() {
        }
        
        public GetVscRatesRequest(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage, string NewUsed, System.DateTime InSrvDate) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Company = Company;
            this.DealerCode = DealerCode;
            this.Vin = Vin;
            this.SaleDate = SaleDate;
            this.Mileage = Mileage;
            this.NewUsed = NewUsed;
            this.InSrvDate = InSrvDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVscRatesResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetVscRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string GetVscRatesResult;
        
        public GetVscRatesResponse() {
        }
        
        public GetVscRatesResponse(string GetVscRatesResult) {
            this.GetVscRatesResult = GetVscRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMaintRates", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetMaintRatesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates")]
        public Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=1)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=2)]
        public string Vin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=3)]
        public System.DateTime SaleDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=4)]
        public string Mileage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=5)]
        public string AloneOption;
        
        public GetMaintRatesRequest() {
        }
        
        public GetMaintRatesRequest(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage, string AloneOption) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Company = Company;
            this.DealerCode = DealerCode;
            this.Vin = Vin;
            this.SaleDate = SaleDate;
            this.Mileage = Mileage;
            this.AloneOption = AloneOption;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMaintRatesResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetMaintRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string GetMaintRatesResult;
        
        public GetMaintRatesResponse() {
        }
        
        public GetMaintRatesResponse(string GetMaintRatesResult) {
            this.GetMaintRatesResult = GetMaintRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRoadHazardRates", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetRoadHazardRatesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates")]
        public Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=1)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=2)]
        public string Vin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=3)]
        public System.DateTime SaleDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=4)]
        public string Mileage;
        
        public GetRoadHazardRatesRequest() {
        }
        
        public GetRoadHazardRatesRequest(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Company = Company;
            this.DealerCode = DealerCode;
            this.Vin = Vin;
            this.SaleDate = SaleDate;
            this.Mileage = Mileage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRoadHazardRatesResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetRoadHazardRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string GetRoadHazardRatesResult;
        
        public GetRoadHazardRatesResponse() {
        }
        
        public GetRoadHazardRatesResponse(string GetRoadHazardRatesResult) {
            this.GetRoadHazardRatesResult = GetRoadHazardRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGapRates", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetGapRatesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates")]
        public Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=1)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=2)]
        public System.DateTime SaleDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=3)]
        public string Mileage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=4)]
        public string Vin;
        
        public GetGapRatesRequest() {
        }
        
        public GetGapRatesRequest(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, System.DateTime SaleDate, string Mileage, string Vin) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Company = Company;
            this.DealerCode = DealerCode;
            this.SaleDate = SaleDate;
            this.Mileage = Mileage;
            this.Vin = Vin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGapRatesResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetGapRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string GetGapRatesResult;
        
        public GetGapRatesResponse() {
        }
        
        public GetGapRatesResponse(string GetGapRatesResult) {
            this.GetGapRatesResult = GetGapRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEtchRates", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetEtchRatesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates")]
        public Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=1)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=2)]
        public string Vin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=3)]
        public System.DateTime SaleDate;
        
        public GetEtchRatesRequest() {
        }
        
        public GetEtchRatesRequest(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Company = Company;
            this.DealerCode = DealerCode;
            this.Vin = Vin;
            this.SaleDate = SaleDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEtchRatesResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetEtchRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string GetEtchRatesResult;
        
        public GetEtchRatesResponse() {
        }
        
        public GetEtchRatesResponse(string GetEtchRatesResult) {
            this.GetEtchRatesResult = GetEtchRatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetChemicalRates", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetChemicalRatesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates")]
        public Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=1)]
        public string DealerCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=2)]
        public string Vin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=3)]
        public System.DateTime SaleDate;
        
        public GetChemicalRatesRequest() {
        }
        
        public GetChemicalRatesRequest(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.Company = Company;
            this.DealerCode = DealerCode;
            this.Vin = Vin;
            this.SaleDate = SaleDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetChemicalRatesResponse", WrapperNamespace="http://UsWarranty.com/UswcWebServiceRates", IsWrapped=true)]
    public partial class GetChemicalRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://UsWarranty.com/UswcWebServiceRates", Order=0)]
        public string GetChemicalRatesResult;
        
        public GetChemicalRatesResponse() {
        }
        
        public GetChemicalRatesResponse(string GetChemicalRatesResult) {
            this.GetChemicalRatesResult = GetChemicalRatesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UswcWebServiceSoapChannel : Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UswcWebServiceSoapClient : System.ServiceModel.ClientBase<Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap>, Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap {
        
        public UswcWebServiceSoapClient() {
        }
        
        public UswcWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UswcWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UswcWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UswcWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetDentRatesResponse Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetDentRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetDentRatesRequest request) {
            return base.Channel.GetDentRates(request);
        }
        
        public string GetDentRates(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetDentRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetDentRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            inValue.Mileage = Mileage;
            Automatrix.Menu.Service.Test.USWarrantyRates.GetDentRatesResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetDentRates(inValue);
            return retVal.GetDentRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetDentRatesResponse> Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetDentRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetDentRatesRequest request) {
            return base.Channel.GetDentRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetDentRatesResponse> GetDentRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetDentRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetDentRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            inValue.Mileage = Mileage;
            return ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetDentRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetEwtRatesResponse Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetEwtRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetEwtRatesRequest request) {
            return base.Channel.GetEwtRates(request);
        }
        
        public string GetEwtRates(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetEwtRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetEwtRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            inValue.Mileage = Mileage;
            Automatrix.Menu.Service.Test.USWarrantyRates.GetEwtRatesResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetEwtRates(inValue);
            return retVal.GetEwtRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetEwtRatesResponse> Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetEwtRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetEwtRatesRequest request) {
            return base.Channel.GetEwtRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetEwtRatesResponse> GetEwtRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetEwtRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetEwtRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            inValue.Mileage = Mileage;
            return ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetEwtRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetKeyRatesResponse Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetKeyRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetKeyRatesRequest request) {
            return base.Channel.GetKeyRates(request);
        }
        
        public string GetKeyRates(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetKeyRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetKeyRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            Automatrix.Menu.Service.Test.USWarrantyRates.GetKeyRatesResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetKeyRates(inValue);
            return retVal.GetKeyRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetKeyRatesResponse> Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetKeyRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetKeyRatesRequest request) {
            return base.Channel.GetKeyRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetKeyRatesResponse> GetKeyRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetKeyRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetKeyRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            return ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetKeyRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetVscRatesResponse Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetVscRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetVscRatesRequest request) {
            return base.Channel.GetVscRates(request);
        }
        
        public string GetVscRates(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage, string NewUsed, System.DateTime InSrvDate) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetVscRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetVscRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            inValue.Mileage = Mileage;
            inValue.NewUsed = NewUsed;
            inValue.InSrvDate = InSrvDate;
            Automatrix.Menu.Service.Test.USWarrantyRates.GetVscRatesResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetVscRates(inValue);
            return retVal.GetVscRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetVscRatesResponse> Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetVscRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetVscRatesRequest request) {
            return base.Channel.GetVscRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetVscRatesResponse> GetVscRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage, string NewUsed, System.DateTime InSrvDate) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetVscRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetVscRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            inValue.Mileage = Mileage;
            inValue.NewUsed = NewUsed;
            inValue.InSrvDate = InSrvDate;
            return ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetVscRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetMaintRatesResponse Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetMaintRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetMaintRatesRequest request) {
            return base.Channel.GetMaintRates(request);
        }
        
        public string GetMaintRates(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage, string AloneOption) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetMaintRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetMaintRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            inValue.Mileage = Mileage;
            inValue.AloneOption = AloneOption;
            Automatrix.Menu.Service.Test.USWarrantyRates.GetMaintRatesResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetMaintRates(inValue);
            return retVal.GetMaintRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetMaintRatesResponse> Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetMaintRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetMaintRatesRequest request) {
            return base.Channel.GetMaintRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetMaintRatesResponse> GetMaintRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage, string AloneOption) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetMaintRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetMaintRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            inValue.Mileage = Mileage;
            inValue.AloneOption = AloneOption;
            return ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetMaintRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetRoadHazardRatesResponse Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetRoadHazardRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetRoadHazardRatesRequest request) {
            return base.Channel.GetRoadHazardRates(request);
        }
        
        public string GetRoadHazardRates(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetRoadHazardRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetRoadHazardRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            inValue.Mileage = Mileage;
            Automatrix.Menu.Service.Test.USWarrantyRates.GetRoadHazardRatesResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetRoadHazardRates(inValue);
            return retVal.GetRoadHazardRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetRoadHazardRatesResponse> Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetRoadHazardRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetRoadHazardRatesRequest request) {
            return base.Channel.GetRoadHazardRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetRoadHazardRatesResponse> GetRoadHazardRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate, string Mileage) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetRoadHazardRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetRoadHazardRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            inValue.Mileage = Mileage;
            return ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetRoadHazardRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetGapRatesResponse Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetGapRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetGapRatesRequest request) {
            return base.Channel.GetGapRates(request);
        }
        
        public string GetGapRates(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, System.DateTime SaleDate, string Mileage, string Vin) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetGapRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetGapRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.SaleDate = SaleDate;
            inValue.Mileage = Mileage;
            inValue.Vin = Vin;
            Automatrix.Menu.Service.Test.USWarrantyRates.GetGapRatesResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetGapRates(inValue);
            return retVal.GetGapRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetGapRatesResponse> Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetGapRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetGapRatesRequest request) {
            return base.Channel.GetGapRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetGapRatesResponse> GetGapRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, System.DateTime SaleDate, string Mileage, string Vin) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetGapRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetGapRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.SaleDate = SaleDate;
            inValue.Mileage = Mileage;
            inValue.Vin = Vin;
            return ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetGapRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetEtchRatesResponse Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetEtchRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetEtchRatesRequest request) {
            return base.Channel.GetEtchRates(request);
        }
        
        public string GetEtchRates(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetEtchRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetEtchRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            Automatrix.Menu.Service.Test.USWarrantyRates.GetEtchRatesResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetEtchRates(inValue);
            return retVal.GetEtchRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetEtchRatesResponse> Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetEtchRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetEtchRatesRequest request) {
            return base.Channel.GetEtchRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetEtchRatesResponse> GetEtchRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetEtchRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetEtchRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            return ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetEtchRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Automatrix.Menu.Service.Test.USWarrantyRates.GetChemicalRatesResponse Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetChemicalRates(Automatrix.Menu.Service.Test.USWarrantyRates.GetChemicalRatesRequest request) {
            return base.Channel.GetChemicalRates(request);
        }
        
        public string GetChemicalRates(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetChemicalRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetChemicalRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            Automatrix.Menu.Service.Test.USWarrantyRates.GetChemicalRatesResponse retVal = ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetChemicalRates(inValue);
            return retVal.GetChemicalRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetChemicalRatesResponse> Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap.GetChemicalRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.GetChemicalRatesRequest request) {
            return base.Channel.GetChemicalRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.USWarrantyRates.GetChemicalRatesResponse> GetChemicalRatesAsync(Automatrix.Menu.Service.Test.USWarrantyRates.AuthenticationHeader AuthenticationHeader, string Company, string DealerCode, string Vin, System.DateTime SaleDate) {
            Automatrix.Menu.Service.Test.USWarrantyRates.GetChemicalRatesRequest inValue = new Automatrix.Menu.Service.Test.USWarrantyRates.GetChemicalRatesRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.Company = Company;
            inValue.DealerCode = DealerCode;
            inValue.Vin = Vin;
            inValue.SaleDate = SaleDate;
            return ((Automatrix.Menu.Service.Test.USWarrantyRates.UswcWebServiceSoap)(this)).GetChemicalRatesAsync(inValue);
        }
    }
}
