//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automatrix.Menu.Service.Test.RoadVantageForm {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/ContractService/", ConfigurationName="RoadVantageForm.ContractServiceSoap")]
    public interface ContractServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContractService/GenerateContract", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceRequest))]
        Automatrix.Menu.Service.Test.RoadVantageForm.GenerateContractResponse GenerateContract(Automatrix.Menu.Service.Test.RoadVantageForm.Contract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContractService/GenerateContract", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.RoadVantageForm.GenerateContractResponse> GenerateContractAsync(Automatrix.Menu.Service.Test.RoadVantageForm.Contract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContractService/PrintContractPDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceRequest))]
        Automatrix.Menu.Service.Test.RoadVantageForm.PrintContractPDFResponse PrintContractPDF(Automatrix.Menu.Service.Test.RoadVantageForm.PrintContractPDFRequest printPDFRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContractService/PrintContractPDF", ReplyAction="*")]
        System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.RoadVantageForm.PrintContractPDFResponse> PrintContractPDFAsync(Automatrix.Menu.Service.Test.RoadVantageForm.PrintContractPDFRequest printPDFRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class Contract : ServiceRequest {
        
        private ContractOption[] contractOptionsField;
        
        private Deductible deductibleField;
        
        private TermMileage termMileField;
        
        private LienHolder lienHolderField;
        
        private Vehicle vehicleField;
        
        private Customer customerField;
        
        private AdditionalContractInfo additionalContractInfoField;
        
        private string contractNumberField;
        
        private string contractFormNumberField;
        
        private string registerNumberField;
        
        private string dealerNumberField;
        
        private System.DateTime inserviceDateField;
        
        private System.DateTime saleDateField;
        
        private System.DateTime vehiclePurchaseDateField;
        
        private int saleOdometerField;
        
        private int manufWarrTermField;
        
        private int manufWarrMilesField;
        
        private decimal vehiclePurchasePriceField;
        
        private string planCodeField;
        
        private int rateBookField;
        
        private bool finalCopyField;
        
        private decimal retailCostField;
        
        private decimal netCostField;
        
        private string financeTypeField;
        
        private System.Nullable<decimal> financedAmountField;
        
        private System.Nullable<decimal> financeAprField;
        
        private System.Nullable<int> financeTermField;
        
        private System.Nullable<decimal> msrpField;
        
        private System.Nullable<decimal> monthlyPaymentField;
        
        private System.DateTime firstPaymentDateField;
        
        private System.Nullable<decimal> balloonAmountField;
        
        private System.Nullable<decimal> residualValueField;
        
        private System.Nullable<decimal> baseACVField;
        
        private System.Nullable<decimal> nADAValueField;
        
        private System.Nullable<decimal> insuranceDeductibleField;
        
        private string salesPersonFnameField;
        
        private string salesPersonLnameField;
        
        private string contractPDFField;
        
        private bool digitallySignedField;
        
        private int quoteIdField;
        
        private bool generateContractDocumentField;
        
        private bool isTaxExemptField;
        
        private System.Nullable<decimal> baseMarkupField;
        
        private System.Nullable<decimal> fIMarkupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ContractOption[] ContractOptions {
            get {
                return this.contractOptionsField;
            }
            set {
                this.contractOptionsField = value;
                this.RaisePropertyChanged("ContractOptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Deductible Deductible {
            get {
                return this.deductibleField;
            }
            set {
                this.deductibleField = value;
                this.RaisePropertyChanged("Deductible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TermMileage TermMile {
            get {
                return this.termMileField;
            }
            set {
                this.termMileField = value;
                this.RaisePropertyChanged("TermMile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public LienHolder LienHolder {
            get {
                return this.lienHolderField;
            }
            set {
                this.lienHolderField = value;
                this.RaisePropertyChanged("LienHolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Vehicle Vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
                this.RaisePropertyChanged("Vehicle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Customer Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("Customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public AdditionalContractInfo AdditionalContractInfo {
            get {
                return this.additionalContractInfoField;
            }
            set {
                this.additionalContractInfoField = value;
                this.RaisePropertyChanged("AdditionalContractInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ContractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
                this.RaisePropertyChanged("ContractNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ContractFormNumber {
            get {
                return this.contractFormNumberField;
            }
            set {
                this.contractFormNumberField = value;
                this.RaisePropertyChanged("ContractFormNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RegisterNumber {
            get {
                return this.registerNumberField;
            }
            set {
                this.registerNumberField = value;
                this.RaisePropertyChanged("RegisterNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DealerNumber {
            get {
                return this.dealerNumberField;
            }
            set {
                this.dealerNumberField = value;
                this.RaisePropertyChanged("DealerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime InserviceDate {
            get {
                return this.inserviceDateField;
            }
            set {
                this.inserviceDateField = value;
                this.RaisePropertyChanged("InserviceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime SaleDate {
            get {
                return this.saleDateField;
            }
            set {
                this.saleDateField = value;
                this.RaisePropertyChanged("SaleDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime VehiclePurchaseDate {
            get {
                return this.vehiclePurchaseDateField;
            }
            set {
                this.vehiclePurchaseDateField = value;
                this.RaisePropertyChanged("VehiclePurchaseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int SaleOdometer {
            get {
                return this.saleOdometerField;
            }
            set {
                this.saleOdometerField = value;
                this.RaisePropertyChanged("SaleOdometer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int ManufWarrTerm {
            get {
                return this.manufWarrTermField;
            }
            set {
                this.manufWarrTermField = value;
                this.RaisePropertyChanged("ManufWarrTerm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int ManufWarrMiles {
            get {
                return this.manufWarrMilesField;
            }
            set {
                this.manufWarrMilesField = value;
                this.RaisePropertyChanged("ManufWarrMiles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal VehiclePurchasePrice {
            get {
                return this.vehiclePurchasePriceField;
            }
            set {
                this.vehiclePurchasePriceField = value;
                this.RaisePropertyChanged("VehiclePurchasePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string PlanCode {
            get {
                return this.planCodeField;
            }
            set {
                this.planCodeField = value;
                this.RaisePropertyChanged("PlanCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int RateBook {
            get {
                return this.rateBookField;
            }
            set {
                this.rateBookField = value;
                this.RaisePropertyChanged("RateBook");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool FinalCopy {
            get {
                return this.finalCopyField;
            }
            set {
                this.finalCopyField = value;
                this.RaisePropertyChanged("FinalCopy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal RetailCost {
            get {
                return this.retailCostField;
            }
            set {
                this.retailCostField = value;
                this.RaisePropertyChanged("RetailCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal NetCost {
            get {
                return this.netCostField;
            }
            set {
                this.netCostField = value;
                this.RaisePropertyChanged("NetCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string FinanceType {
            get {
                return this.financeTypeField;
            }
            set {
                this.financeTypeField = value;
                this.RaisePropertyChanged("FinanceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<decimal> FinancedAmount {
            get {
                return this.financedAmountField;
            }
            set {
                this.financedAmountField = value;
                this.RaisePropertyChanged("FinancedAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<decimal> FinanceApr {
            get {
                return this.financeAprField;
            }
            set {
                this.financeAprField = value;
                this.RaisePropertyChanged("FinanceApr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public System.Nullable<int> FinanceTerm {
            get {
                return this.financeTermField;
            }
            set {
                this.financeTermField = value;
                this.RaisePropertyChanged("FinanceTerm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<decimal> Msrp {
            get {
                return this.msrpField;
            }
            set {
                this.msrpField = value;
                this.RaisePropertyChanged("Msrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<decimal> MonthlyPayment {
            get {
                return this.monthlyPaymentField;
            }
            set {
                this.monthlyPaymentField = value;
                this.RaisePropertyChanged("MonthlyPayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public System.DateTime FirstPaymentDate {
            get {
                return this.firstPaymentDateField;
            }
            set {
                this.firstPaymentDateField = value;
                this.RaisePropertyChanged("FirstPaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<decimal> BalloonAmount {
            get {
                return this.balloonAmountField;
            }
            set {
                this.balloonAmountField = value;
                this.RaisePropertyChanged("BalloonAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<decimal> ResidualValue {
            get {
                return this.residualValueField;
            }
            set {
                this.residualValueField = value;
                this.RaisePropertyChanged("ResidualValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public System.Nullable<decimal> BaseACV {
            get {
                return this.baseACVField;
            }
            set {
                this.baseACVField = value;
                this.RaisePropertyChanged("BaseACV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public System.Nullable<decimal> NADAValue {
            get {
                return this.nADAValueField;
            }
            set {
                this.nADAValueField = value;
                this.RaisePropertyChanged("NADAValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public System.Nullable<decimal> InsuranceDeductible {
            get {
                return this.insuranceDeductibleField;
            }
            set {
                this.insuranceDeductibleField = value;
                this.RaisePropertyChanged("InsuranceDeductible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string SalesPersonFname {
            get {
                return this.salesPersonFnameField;
            }
            set {
                this.salesPersonFnameField = value;
                this.RaisePropertyChanged("SalesPersonFname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string SalesPersonLname {
            get {
                return this.salesPersonLnameField;
            }
            set {
                this.salesPersonLnameField = value;
                this.RaisePropertyChanged("SalesPersonLname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string ContractPDF {
            get {
                return this.contractPDFField;
            }
            set {
                this.contractPDFField = value;
                this.RaisePropertyChanged("ContractPDF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public bool DigitallySigned {
            get {
                return this.digitallySignedField;
            }
            set {
                this.digitallySignedField = value;
                this.RaisePropertyChanged("DigitallySigned");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public int QuoteId {
            get {
                return this.quoteIdField;
            }
            set {
                this.quoteIdField = value;
                this.RaisePropertyChanged("QuoteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public bool GenerateContractDocument {
            get {
                return this.generateContractDocumentField;
            }
            set {
                this.generateContractDocumentField = value;
                this.RaisePropertyChanged("GenerateContractDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public bool IsTaxExempt {
            get {
                return this.isTaxExemptField;
            }
            set {
                this.isTaxExemptField = value;
                this.RaisePropertyChanged("IsTaxExempt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=42)]
        public System.Nullable<decimal> BaseMarkup {
            get {
                return this.baseMarkupField;
            }
            set {
                this.baseMarkupField = value;
                this.RaisePropertyChanged("BaseMarkup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=43)]
        public System.Nullable<decimal> FIMarkup {
            get {
                return this.fIMarkupField;
            }
            set {
                this.fIMarkupField = value;
                this.RaisePropertyChanged("FIMarkup");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class ContractOption : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string descriptionField;
        
        private bool isSurchargeField;
        
        private decimal netCostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsSurcharge {
            get {
                return this.isSurchargeField;
            }
            set {
                this.isSurchargeField = value;
                this.RaisePropertyChanged("IsSurcharge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal NetCost {
            get {
                return this.netCostField;
            }
            set {
                this.netCostField = value;
                this.RaisePropertyChanged("NetCost");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int typeField;
        
        private string codeField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrintContractPDFResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenerateContractResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class ServiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int responseCodeField;
        
        private Message[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Message[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("Messages");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class PrintContractPDFResponse : ServiceResponse {
        
        private string contractPDFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContractPDF {
            get {
                return this.contractPDFField;
            }
            set {
                this.contractPDFField = value;
                this.RaisePropertyChanged("ContractPDF");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class GenerateContractResponse : ServiceResponse {
        
        private string contractDocumentField;
        
        private string contractNumberField;
        
        private System.DateTime effectiveDateField;
        
        private int effectiveOdometerField;
        
        private System.DateTime expirationDateField;
        
        private int expirationOdometerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContractDocument {
            get {
                return this.contractDocumentField;
            }
            set {
                this.contractDocumentField = value;
                this.RaisePropertyChanged("ContractDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ContractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
                this.RaisePropertyChanged("ContractNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime EffectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
                this.RaisePropertyChanged("EffectiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int EffectiveOdometer {
            get {
                return this.effectiveOdometerField;
            }
            set {
                this.effectiveOdometerField = value;
                this.RaisePropertyChanged("EffectiveOdometer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ExpirationOdometer {
            get {
                return this.expirationOdometerField;
            }
            set {
                this.expirationOdometerField = value;
                this.RaisePropertyChanged("ExpirationOdometer");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class AdditionalContractInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int fieldOrderField;
        
        private string fieldLabelField;
        
        private string fieldValueField;
        
        private string fieldTypeField;
        
        private int lengthField;
        
        private bool requiredField;
        
        private bool uniqueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FieldOrder {
            get {
                return this.fieldOrderField;
            }
            set {
                this.fieldOrderField = value;
                this.RaisePropertyChanged("FieldOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FieldLabel {
            get {
                return this.fieldLabelField;
            }
            set {
                this.fieldLabelField = value;
                this.RaisePropertyChanged("FieldLabel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FieldValue {
            get {
                return this.fieldValueField;
            }
            set {
                this.fieldValueField = value;
                this.RaisePropertyChanged("FieldValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FieldType {
            get {
                return this.fieldTypeField;
            }
            set {
                this.fieldTypeField = value;
                this.RaisePropertyChanged("FieldType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("Length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
                this.RaisePropertyChanged("Required");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool Unique {
            get {
                return this.uniqueField;
            }
            set {
                this.uniqueField = value;
                this.RaisePropertyChanged("Unique");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipCodeField;
        
        private string homePhoneField;
        
        private string homePhoneExtField;
        
        private string workPhoneField;
        
        private string workPhoneExtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string HomePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
                this.RaisePropertyChanged("HomePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string HomePhoneExt {
            get {
                return this.homePhoneExtField;
            }
            set {
                this.homePhoneExtField = value;
                this.RaisePropertyChanged("HomePhoneExt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string WorkPhone {
            get {
                return this.workPhoneField;
            }
            set {
                this.workPhoneField = value;
                this.RaisePropertyChanged("WorkPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string WorkPhoneExt {
            get {
                return this.workPhoneExtField;
            }
            set {
                this.workPhoneExtField = value;
                this.RaisePropertyChanged("WorkPhoneExt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class Customer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string middleInitialField;
        
        private string emailField;
        
        private Address addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MiddleInitial {
            get {
                return this.middleInitialField;
            }
            set {
                this.middleInitialField = value;
                this.RaisePropertyChanged("MiddleInitial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class Vehicle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cylField;
        
        private string fuelField;
        
        private string modelField;
        
        private string drvField;
        
        private string vinNumberField;
        
        private string makeField;
        
        private int yearField;
        
        private string vehicleTypeField;
        
        private string aspirationCodeField;
        
        private string segmentationCodeField;
        
        private string tonRatingField;
        
        private string gVWRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Cyl {
            get {
                return this.cylField;
            }
            set {
                this.cylField = value;
                this.RaisePropertyChanged("Cyl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Fuel {
            get {
                return this.fuelField;
            }
            set {
                this.fuelField = value;
                this.RaisePropertyChanged("Fuel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
                this.RaisePropertyChanged("Model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Drv {
            get {
                return this.drvField;
            }
            set {
                this.drvField = value;
                this.RaisePropertyChanged("Drv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string VinNumber {
            get {
                return this.vinNumberField;
            }
            set {
                this.vinNumberField = value;
                this.RaisePropertyChanged("VinNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
                this.RaisePropertyChanged("Make");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string VehicleType {
            get {
                return this.vehicleTypeField;
            }
            set {
                this.vehicleTypeField = value;
                this.RaisePropertyChanged("VehicleType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AspirationCode {
            get {
                return this.aspirationCodeField;
            }
            set {
                this.aspirationCodeField = value;
                this.RaisePropertyChanged("AspirationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SegmentationCode {
            get {
                return this.segmentationCodeField;
            }
            set {
                this.segmentationCodeField = value;
                this.RaisePropertyChanged("SegmentationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TonRating {
            get {
                return this.tonRatingField;
            }
            set {
                this.tonRatingField = value;
                this.RaisePropertyChanged("TonRating");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string GVWR {
            get {
                return this.gVWRField;
            }
            set {
                this.gVWRField = value;
                this.RaisePropertyChanged("GVWR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class LienHolder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stateField;
        
        private string phoneField;
        
        private string cityField;
        
        private string zipCodeField;
        
        private string nameField;
        
        private string address1Field;
        
        private string address2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class TermMileage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int termIdField;
        
        private int termField;
        
        private int mileageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TermId {
            get {
                return this.termIdField;
            }
            set {
                this.termIdField = value;
                this.RaisePropertyChanged("TermId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Term {
            get {
                return this.termField;
            }
            set {
                this.termField = value;
                this.RaisePropertyChanged("Term");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Mileage {
            get {
                return this.mileageField;
            }
            set {
                this.mileageField = value;
                this.RaisePropertyChanged("Mileage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class GlobalInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cultureNameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CultureName {
            get {
                return this.cultureNameField;
            }
            set {
                this.cultureNameField = value;
                this.RaisePropertyChanged("CultureName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class Deductible : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GlobalInformation[] deductTypeDescriptionsField;
        
        private int deductIdField;
        
        private decimal deductAmtField;
        
        private string deductTypeField;
        
        private decimal reducedAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public GlobalInformation[] DeductTypeDescriptions {
            get {
                return this.deductTypeDescriptionsField;
            }
            set {
                this.deductTypeDescriptionsField = value;
                this.RaisePropertyChanged("DeductTypeDescriptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DeductId {
            get {
                return this.deductIdField;
            }
            set {
                this.deductIdField = value;
                this.RaisePropertyChanged("DeductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal DeductAmt {
            get {
                return this.deductAmtField;
            }
            set {
                this.deductAmtField = value;
                this.RaisePropertyChanged("DeductAmt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DeductType {
            get {
                return this.deductTypeField;
            }
            set {
                this.deductTypeField = value;
                this.RaisePropertyChanged("DeductType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal ReducedAmount {
            get {
                return this.reducedAmountField;
            }
            set {
                this.reducedAmountField = value;
                this.RaisePropertyChanged("ReducedAmount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrintContractPDFRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Contract))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class ServiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIdField;
        
        private string passwordField;
        
        private string tpaCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TpaCode {
            get {
                return this.tpaCodeField;
            }
            set {
                this.tpaCodeField = value;
                this.RaisePropertyChanged("TpaCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ContractService/")]
    public partial class PrintContractPDFRequest : ServiceRequest {
        
        private string contractNumberField;
        
        private string dealerNumberField;
        
        private string requestingUserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
                this.RaisePropertyChanged("ContractNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DealerNumber {
            get {
                return this.dealerNumberField;
            }
            set {
                this.dealerNumberField = value;
                this.RaisePropertyChanged("DealerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RequestingUser {
            get {
                return this.requestingUserField;
            }
            set {
                this.requestingUserField = value;
                this.RaisePropertyChanged("RequestingUser");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContractServiceSoapChannel : Automatrix.Menu.Service.Test.RoadVantageForm.ContractServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContractServiceSoapClient : System.ServiceModel.ClientBase<Automatrix.Menu.Service.Test.RoadVantageForm.ContractServiceSoap>, Automatrix.Menu.Service.Test.RoadVantageForm.ContractServiceSoap {
        
        public ContractServiceSoapClient() {
        }
        
        public ContractServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContractServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Automatrix.Menu.Service.Test.RoadVantageForm.GenerateContractResponse GenerateContract(Automatrix.Menu.Service.Test.RoadVantageForm.Contract contract) {
            return base.Channel.GenerateContract(contract);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.RoadVantageForm.GenerateContractResponse> GenerateContractAsync(Automatrix.Menu.Service.Test.RoadVantageForm.Contract contract) {
            return base.Channel.GenerateContractAsync(contract);
        }
        
        public Automatrix.Menu.Service.Test.RoadVantageForm.PrintContractPDFResponse PrintContractPDF(Automatrix.Menu.Service.Test.RoadVantageForm.PrintContractPDFRequest printPDFRequest) {
            return base.Channel.PrintContractPDF(printPDFRequest);
        }
        
        public System.Threading.Tasks.Task<Automatrix.Menu.Service.Test.RoadVantageForm.PrintContractPDFResponse> PrintContractPDFAsync(Automatrix.Menu.Service.Test.RoadVantageForm.PrintContractPDFRequest printPDFRequest) {
            return base.Channel.PrintContractPDFAsync(printPDFRequest);
        }
    }
}
